# Generated by Django 3.2.4 on 2022-10-12 10:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('first_level', models.CharField(blank=True, max_length=255, verbose_name='Первый уровень')),
                ('second_level', models.CharField(blank=True, max_length=255, verbose_name='Второй уровень')),
                ('third_level', models.CharField(blank=True, max_length=255, verbose_name='Третий уровень')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('price_sp', models.PositiveIntegerField(verbose_name='ЦенаСП')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('property_fields', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Поля свойств')),
                ('purchases', models.TextField(blank=True, verbose_name='Совместные покупки')),
                ('unit', models.CharField(max_length=255, verbose_name='Единица измерения')),
                ('image', models.ImageField(blank=True, upload_to='home', verbose_name='Картинка')),
                ('is_on_index', models.BooleanField(default=False, verbose_name='Вывод на главную страницу')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
