# Generated by Django 3.2.4 on 2022-10-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(upload_to='home', verbose_name='CSV-файл'),
        ),
    ]
