# Generated by Django 3.2.4 on 2022-10-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_csvfile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvfile',
            options={'verbose_name': 'CSV-файл', 'verbose_name_plural': 'CSV-файлы'},
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='code',
            field=models.PositiveIntegerField(blank=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='count',
            field=models.IntegerField(blank=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='price',
            field=models.PositiveIntegerField(blank=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='price_sp',
            field=models.PositiveIntegerField(blank=True, verbose_name='ЦенаСП'),
        ),
    ]
