# Generated by Django 3.2.4 on 2022-10-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221012_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Код'),
        ),
    ]
