# Generated by Django 3.2.4 on 2022-10-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_goodsmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='price_sp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ЦенаСП'),
        ),
    ]
