# Generated by Django 3.2.4 on 2022-10-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221012_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CsvFile',
        ),
    ]
